upload_max_filesize = 32M
post_max_size = 32M
memory_limit = 512M
max_execution_time = 120
max_input_vars = 3000

[opcache]
opcache.enable=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=2
